// This file is part of Visual D
//
// Visual D integrates the D programming language into Visual Studio
// Copyright (c) 2012 by Rainer Schuetze, All Rights Reserved
//
// License for redistribution is given by the Artistic License 2.0
// see file LICENSE for further details

// bring in core IDL files
import "oaidl.idl";

[
	object,
	uuid(002a2de9-8bb6-484d-9901-7e4ad4084715),
	dual,
	nonextensible,
	helpstring("IVDServer Interface"),
	pointer_default(unique)
]
interface IVDServer : IUnknown
{
	HRESULT ExecCommand([in]BSTR cmd, [out,retval] BSTR* answer);
	HRESULT ExecCommandAsync([in]BSTR cmd, [out,retval] ULONG* cmdID);

	HRESULT ConfigureSemanticProject([in] BSTR imp, [in] BSTR stringImp, [in] BSTR versionids, [in] BSTR debugids, [in] DWORD flags);
	HRESULT ClearSemanticProject();
	HRESULT UpdateModule([in] BSTR filename, [in] BSTR srcText);
	HRESULT GetType([in] BSTR filename, [in,out] DWORD *startLine, [in,out] DWORD *startIndex, [in,out] DWORD *endLine, [in,out] DWORD *endIndex, [out,retval] BSTR* answer);
	HRESULT GetSemanticExpansions([in] BSTR filename, [in] BSTR tok, [in] DWORD line, [in] DWORD idx, [out,retval] BSTR* stringList);
	HRESULT IsBinaryOperator([in] BSTR filename, [in] DWORD startLine, [in] DWORD startIndex, [in] DWORD endLine, [in] DWORD endIndex, [out,retval] BOOL* pIsOp);
	HRESULT GetParseErrors([in] BSTR filename, [out,retval] BSTR* errors);
};

// library statement
[uuid(002a2de9-8bb6-484d-9903-7e4ad4084715), version(1.0),
 helpstring("Visual D Semantic Server")]
library VDServerLib
{
   importlib("stdole32.tlb");
   [uuid(002a2de9-8bb6-484d-9902-7e4ad4084715)]
   coclass VDServerClassFactory
   {
      [default] interface IVDServer;
   };
};

